profileOne = { "name":"Billy Bob", "email":"billbob@gmail.com", "password":"4444", "handle":"@billybob", "location":"Paris, France", "interests":"dining, outdoors", "activities":"hiking, paddle boating, dining", "aboutYou":"My name is Billy Bob. I am know Paris very well and will show you all the most delicious foods to eat.", "profilePhoto":"https://media.gq.com/photos/56d75ae39acdcf20275f0f4e/master/pass/1-courtesy%20of%20Gucci.jpg", "coverPhoto":"https://www.musictick.com/img/slide/slide_parigi.jpg", "host":true, "hostee":false };

profileTWO = { "name":"Barbara", "email":"babs241@yahoo.com", "password":"4444", "handle":"@babs", "location":"San Francisco, CA", "interests":"clubbing and museums", "activities":"dancing, museums and art", "aboutYou":"Hello! My name is Barbara, I will  travelling to San Francisco next month and would love to see all the amazing museums, art and clubs in the city", "profilePhoto":"http://djbrecord.free.fr/barbara019.jpg", "coverPhoto":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSnlmU5YssZUd8aAgKIG5Yl8aBsBqdv7fyJc0K5cdzKpWTLYGq", "host":false, "hostee":true };

profileThree = { "name":"Deb Rah", "email":"debdeb@outlook.com", "password":"4444", "handle":"@debdeb", "location":"Buenos Aires, Argentina", "interests":"outdoors and camping", "activities":"hiking, biking, exploring", "aboutYou":"My name is Deb and I live in Buenos Aires. I love everything outdoors and adventure and can show you the beautiful landscapes near by my home town.", "profilePhoto":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHAmgX2ahZ3zYUo9iP4iTfgz2Lrn2B8Jk6V1SXmFljRoZarYUUQA", "coverPhoto":"https://www.zicasso.com/sites/default/files/styles/original_scaled_down/public/photos/review/1583777/braziliguassufalls-gapargentinaadventure.jpg", "host":true, "hostee":false };

profileFour = { "name":"Frank", "email":"fbomb@aol.com", "password":"4444", "handle":"@frankie", "location":"Sydney, Australia", "interests":"I want to see new things and everything Sydney has to offers", "activities":"exploring, dining and drinking", "aboutYou":"I am friendly, chill and enjoy exploring and having a good time", "profilePhoto":"http://www.sinatra.com/sites/default/files/styles/news-thumbnail/public/Frank%20Sinatra%202.25.15%20site%20post.jpg?itok=bH18he2V", "coverPhoto":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyIQ860p-8HW9rkHdCpDr3Qm4vh5IDii4cM4n4wgMW47s9v2bYeQ", "host":false, "hostee":true };

profileFive = { "name":"Michelle B.", "email":"michelleyb123@ymail.com", "password":"4444", "handle":"@michelle", "location":"Montreal, Québec, Canada", "interests":"outdoors and dining", "activities":"snowboarding, skiing, cooking and going out to eat", "aboutYou":"My name is Michelle and I live in Québec. I love to play in the snow and cook delicious meals at home. I can show you near by ski and snowboard mountains to spend the day at.", "profilePhoto":"https://assets.vogue.com/photos/58584b45a6984b8c49fabbb0/master/pass/michelle-ruiz.jpg", "coverPhoto":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJbvXxf_xVcV-70WGOTO7lniI3e7huHfCW_AebxCZVk_mcQFB6", "host":true, "hostee":false };

profileSix = { "name":"Robert O.", "email":"roberto@)mail.com", "password":"4444", "handle":"@robert0321", "location":"Moscow, Russia", "interests":"drinking", "activities":"drinking activities", "aboutYou":"Hi my name is Robert and I am coming to Moscow in August from Poland. I want to have a good time and experience all that the city has to offer", "profilePhoto":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCF9BCQDhciXJOPcT1XB5RHpxXGpJ0STjbQEWwrGyxNVsF7PAI", "coverPhoto":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQr6UFU4iukLjxM4ez5Eaf088fP35O-eER_lcmNOAexf_ZsHmov", "host":false, "hostee":true };

profileSeven = { "name":"Mary Poppins", "email":"mpoppins@gmail.com", "password":"4444", "handle":"@marypoppins", "location":"London, England", "interests":"tea and spoons full of sugar", "activities":"tea parties and flying", "aboutYou":"Hello I am Mary Poppins and live in London, England. I can show you all of the sights of my town. I grew up here and know all of its history.", "profilePhoto":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2SaJVA3LVxB6BdAtystS1rJgWlhH-u-8dswqtTVlfsA7tpRPq", "coverPhoto":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToWPG_bGU5Bkhk7HmA-biwzMP0jHKtAWvPY5FV7U7KXWg8FNNgDQ", "host":true, "hostee":false };

profileEight = { "name":"Martin Luther", "email":"mluther@yahoo.com", "password":"4444", "handle":"@martin", "location":"New York City", "interests":"art", "activities":"art walks, art shows, museums", "aboutYou":"Hi my name is Martin. I am a host  in New York City and love art and museums.", "profilePhoto":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIAaEOJ8qdWhTbk7DP-Ylr_RzYd4l1kGzGC0ZQ1fEiQvqH6iYHPA", "coverPhoto":"https://media.wired.com/photos/59443560e8e2f01290fc76ab/master/pass/iStock-501796588.jpg", "host":true, "hostee":false };

profileNine = { "name":"Mickey Mouse", "email":"mickey123@disney.com", "password":"4444", "handle":"@mickeymouse", "location":"Chiang Mai, Thailand", "interests":"animals", "activities":"caring for elephants, hiking, nature", "aboutYou":"Hi I am Mickey and I am travelling to Thailand. I want to visit an Elephant Sanctuary in Chiang Mai", "profilePhoto":"https://www.emmys.com/sites/default/files/styles/show_detail/public/disney-mickey-mouse-600x600.jpg?itok=37-ghpD0", "coverPhoto":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDLYkqbEvRCTnJF4c27S5mMLD-3IMcKyEd1-SKqG37s6OTxucZAw", "host":false, "hostee":true };

profileTen = { "name":"Donald D.", "email":"donald_d@gmail.com", "password":"4444", "handle":"@donald", "location":"Cape Town, South Africa", "interests":"dining, boats", "activities":"swimming, snorkeling, fishing, boating", "aboutYou":"Hi I am Donald. I am traveling to Cape Town and want to explore, dine and play in the water", "profilePhoto":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxTv_ycswr8-VuWAKlrBSKCxgnc-npc5SJ7qH3tUZsSBmiIbIJIw", "coverPhoto":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4SVsIwVY-91nTU15aVxlJWZ_XrgsJzFtRknZKS8WXjb-hrA5tOw", "host":false, "hostee":true };

profileEleven = { "name":"Kitty", "email":"meow@gmail.com", "password":"4444", "handle":"@kittycat", "location":"London, England", "interests":"painting, swimming, art", "activities":"museum tours, art walks, swimming and canoeing", "aboutYou":"Hi my name is Kitty. I am visiting England next month and would  love to find someone to take me to their favorite museums and art exhibits around the city", "profilePhoto":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsq4mTZ7bX-SKBpLkL_P9a6KGdbN9EoMxMwoAOLFaozEgn9eCo7w", "coverPhoto":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzBLw46wlxX1dUzLYhZhah0bQCMfIgo5erdw9gNl3hBY__isHp6w", "host":false, "hostee":true };

profilTwelve = { "name":"Lucy", "email":"ilovelucy@yahoo.com", "password":"4444", "handle":"@lucyyyy", "location":"London, England", "interests":"dancing, singing", "activities":"dancing, singing, enjoying life", "aboutYou":"Hi I am Lucy, I live in London and love exploring and showing travelers around my town. I am very knowledgable when it comes to dance, art and shows", "profilePhoto":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwu7IjSV40tJ8ClzY-dLZygJvmfzRzqxookEALTkYcYy0xFuTxFw", "coverPhoto":"https://i.ytimg.com/vi/PtWeqZsuzpE/maxresdefault.jpg", "host":true, "hostee":false };